server:
  port: 8080
spring:
  config:
    import: optional:configserver:http://localhost:8888
  boot:
    admin:
      client:
        url: http://localhost:9090

management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      show-details: always